const AUTH_USER = {
  REQUEST: "AUTH_USER_REQUEST",
  SUCCESS: "AUTH_USER_SUCCEED",
  FAIL: "AUTH_USER_FAIL",
  CLEAN: "AUTH_USER_CLEAN",
  GET_INFO_REQUEST: "AUTH_USER_GET_INFO_REQUEST",
  GET_INFO_SUCCESS: "AUTH_USER_GET_INFO_SUCCESS",
  GET_INFO_FAIL: "AUTH_USER_GET_INFO_FAIL",
};

const REGISTER_USER = {
  REQUEST: "REGISTER_USER_REQUEST",
  SUCCESS: "REGISTER_USER_SUCCESS",
  FAIL: "REGISTER_USER_FAIL",
};

const SHIPMENTS = {
  REQUEST: "SHIPMENTS_REQUEST",
  SUCCESS: "SHIPMEENTS_SUCCESS",
  FAIL: "SHIPMENTS_FAIL",
  OPEN_DRAWER: "SHIPMENTS_OPEN_DRAWER",
  ADD: "ADD_SHIPMENT",
  ADD_SUCCESS: "ADD_SHIPMENT_SUCCESS",
  ADD_FAIL: "ADD_SHIPMENT_FAIL",
  REMOVE: "REMOVE_SHIPMENT",
  REMOVE_SUCCESS: "REMOVE_SHIPMENT_SUCCESS",
  REMOVE_FAIL: "REMOVE_SHIPMENT_FAIL",
};

const SIDEBAR_STATE = {
  DESKTOP: "SIDEBAR_STATE_DESKTOP",
  MOBILE: "SIDEBAR_STATE_MOBILE",
  CLEAN: "SIDEBAR_STATE_CLEAN",
};

export { AUTH_USER, SIDEBAR_STATE, SHIPMENTS, REGISTER_USER };
